### PR TITLE
Fix `apply-settings.sh`

### PR DESCRIPTION
**Pull request by kivlor**
This should fix issue #13 XS

### CODE REVIEW

**Comment by samrocketman** [comment]
I should have reviewed more closely.  This fixes nothing.  All you did was make a subshell not a subshell and it isn’t related to server options.  It starts a simple HTTP server for custom maps.

I’ll pay closer attn next time.  Please refer to the bash manual.

**Comment by samrocketman** [comment]
Please open another without changing subshell behavior.  The fix you added was the `fi`; I misspoke

**Comment by samrocketman** [comment]
I did a revert of my revert but applied code suggestions in #16 .  I am AFK at the moment so am only using web UI.  Apologies for my earlier comments.

**Comment by kivlor** [comment]
all good, I see what you mean about the subshell now 👍

**Comment by samrocketman** [comment]
Thanks for the fix :smile: for completeness in case you or any lurkers were curious; I meant to link bash docs in my earlier comment.

* [Shell functions](https://www.gnu.org/software/bash/manual/bash.html#Shell-Functions)
* https://www.gnu.org/software/bash/manual/bash.html#Compound-Commands

Generic function definition

```
function fname [()] compound-command [ redirections ]
```

Meaning a function can take any compound command.  This is very unlike other programming languages where functions always have curly braces.  For example the following is a valid shell function.

```bash
function prefix() while read x; do echo "[my prefix] $x"; done
```

A function can contain any compound command and in my script I'm using [subshell `()` instead of a non-subshell group `{}`][1].

[1]: https://www.gnu.org/software/bash/manual/bash.html#Command-Grouping

**Pull request merged**
